"""
FastAPI Application Transaction Service


Initializes FastAPI app, registers routes, and configures exception handlers.
Implements RBAC authorization for all transaction endpoints.

Features:
- Async database connection pooling
- JWT-based role-based access control (RBAC)
- Proper lifespan management (startup/shutdown)
- CORS middleware for inter-service communication
- Exception handling for all transaction errors
- API documentation at /api/v1/docs
"""

import logging
import sys
from pathlib import Path
from fastapi import FastAPI, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.openapi.utils import get_openapi
from contextlib import asynccontextmanager
from datetime import datetime

from app.config.settings import settings
from app.database.db import database
from app.exceptions.transaction_exceptions import TransactionException

# Import JWT configuration from Auth Service
auth_service_path = str(Path(__file__).parent.parent.parent / "auth_service" / "app")
if auth_service_path not in sys.path:
    sys.path.insert(0, auth_service_path)

try:
    from security.auth_dependencies import set_jwt_config
except ImportError:
    # Fallback if auth_service is in different location
    auth_service_path = str(Path(__file__).parent.parent.parent / "auth_service")
    if auth_service_path not in sys.path:
        sys.path.insert(0, auth_service_path)
    from app.security.auth_dependencies import set_jwt_config

# Import routers
from app.api.deposit_routes import router as deposit_router
from app.api.withdraw_routes import router as withdraw_router
from app.api.transfer_routes import router as transfer_router
from app.api.transfer_limit_routes import router as transfer_limit_router
from app.api.transaction_log_routes import router as transaction_log_router
from app.api.frontend_routes import router as frontend_router  # Frontend-compatible routes

# Configure logging
from logging.handlers import RotatingFileHandler
import os

# Create logs directory
log_dir = settings.LOG_DIR
os.makedirs(log_dir, exist_ok=True)
log_file = os.path.join(log_dir, "service.log")

# File handler for transaction logs
file_handler = RotatingFileHandler(
    log_file, maxBytes=10*1024*1024, backupCount=5
)
file_handler.setLevel(logging.INFO)
file_handler.setFormatter(logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
))

# Root logger
root_logger = logging.getLogger()
root_logger.addHandler(file_handler)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(),
        file_handler
    ]
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.
    Handles startup and shutdown events properly.
    """
    # Startup
    logger.info("🚀 Starting Transaction Service")
    logger.info(f"📊 Database: {settings.DB_HOST}:{settings.DB_PORT}/{settings.DB_NAME}")
    logger.info(f"💰 Account Service: {settings.ACCOUNT_SERVICE_URL}")
    
    # Initialize JWT configuration for authorization
    try:
        set_jwt_config(settings.JWT_SECRET_KEY, settings.JWT_ALGORITHM)
        logger.info("✅ JWT configuration initialized for RBAC")
    except Exception as e:
        logger.error(f"❌ Failed to initialize JWT config: {str(e)}")
        raise
    
    try:
        await database.initialize()
        logger.info("✅ Database connection pool initialized")
    except Exception as e:
        logger.error(f"❌ Failed to initialize database: {str(e)}")
        raise
    
    yield
    
    # Shutdown
    logger.info("👋 Shutting down Transaction Service")
    try:
        await database.close()
        logger.info("✅ Database connection pool closed")
    except Exception as e:
        logger.error(f"❌ Error closing database: {str(e)}")


# Initialize FastAPI app with lifespan management
app = FastAPI(
    title="Global Digital Bank - Transaction Service",
    description="Microservice for handling withdrawals, deposits, transfers, and transaction logging",
    version="1.0.0",
    lifespan=lifespan,
    docs_url="/api/v1/docs",
    redoc_url="/api/v1/redoc",
    openapi_url="/api/v1/openapi.json",
)

# Add OpenAPI security scheme for Bearer token
def custom_openapi():
    """Custom OpenAPI schema with Bearer token security."""
    if app.openapi_schema:
        return app.openapi_schema
    
    # Get the default OpenAPI schema generated by FastAPI
    openapi_schema = get_openapi(
        title="Global Digital Bank - Transaction Service",
        version="1.0.0",
        description="Microservice for handling withdrawals, deposits, transfers, and transaction logging",
        routes=app.routes,
    )
    
    # Add Bearer token security scheme
    openapi_schema["components"]["securitySchemes"] = {
        "Bearer": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "JWT Bearer token. Get from Auth Service /login endpoint",
        }
    }
    
    # Apply security to all endpoints
    openapi_schema["security"] = [{"Bearer": []}]
    
    app.openapi_schema = openapi_schema
    return app.openapi_schema

app.openapi = custom_openapi

# CORS middleware - allow calls from other services
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=r"https?://(localhost|127\.0\.0\.1)(:\d+)?|https?://.*\.onrender\.com",
    allow_origins=settings.CORS_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Health check endpoint
@app.get(
    "/api/v1/health",
    status_code=status.HTTP_200_OK,
    tags=["Health"],
    summary="Health Check",
)
async def health_check():
    """
    Check if service is running and database is connected.

    Returns 200 OK if healthy.
    """
    return {
        "status": "healthy",
        "service": "Transaction Service",
        "version": "1.0.0",
    }


# API Info endpoint at root
@app.get(
    "/",
    status_code=status.HTTP_200_OK,
    tags=["Info"],
    summary="API Information",
)
async def root():
    """
    Root endpoint with service information and available endpoints.
    """
    return {
        "service": "Global Digital Bank - Transaction Service",
        "version": "1.0.0",
        "description": "Microservice for handling withdrawals, deposits, transfers, and transaction logging",
        "status": "running",
        "docs": "/api/v1/docs",
        "health": "/api/v1/health",
        "endpoints": {
            "deposits": "/api/v1/deposits",
            "withdrawals": "/api/v1/withdrawals",
            "transfers": "/api/v1/transfers",
            "transfer_limits": "/api/v1/transfer-limits",
            "transaction_logs": "/api/v1/transaction-logs",
        },
        "timestamp": datetime.now().isoformat(),
    }


# Ready check endpoint
@app.get(
    "/ready",
    status_code=status.HTTP_200_OK,
    tags=["Health"],
    summary="Readiness Check",
)
async def readiness_check():
    """
    Check if service is ready to handle requests.

    Returns 200 OK if database is connected and service is ready.
    """
    return {
        "status": "ready",
        "service": "Transaction Service",
        "database": "connected",
    }


# Include all route routers for transaction operations
app.include_router(deposit_router)
app.include_router(withdraw_router)
app.include_router(transfer_router)
app.include_router(transfer_limit_router)
app.include_router(transaction_log_router)
app.include_router(frontend_router)  # Frontend-compatible routes (/api/v1/transactions/*)


# ... imports ...
try:
    from app.utils.error_logger import log_error, log_business_logic_error
except ImportError:
    # Fallback if utils not available
    def log_error(service, error, **kwargs):
        logging.getLogger("fallback").error(str(error))
    def log_business_logic_error(service, error, **kwargs):
        logging.getLogger("fallback").warning(str(error))

# ... existing code ...

# Global exception handler for TransactionException
@app.exception_handler(TransactionException)
async def transaction_exception_handler(request, exc: TransactionException):
    """Handle all transaction-related exceptions."""
    log_business_logic_error("transactions_service", exc, operation=request.url.path, details={"error_code": exc.error_code})
    
    return JSONResponse(
        status_code=exc.http_code,
        content={
            "error_code": exc.error_code,
            "message": exc.message,
            "status": "error",
        },
    )


# Global exception handler for unhandled exceptions
@app.exception_handler(Exception)
async def general_exception_handler(request, exc: Exception):
    """Handle all unhandled exceptions."""
    log_error("transactions_service", exc, endpoint=str(request.url), severity="CRITICAL")

    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={
            "error_code": "INTERNAL_ERROR",
            "message": "Internal server error",
            "status": "error",
        },
    )


# Root endpoint
@app.get(
    "/",
    tags=["Info"],
    summary="API Info",
)
async def root():
    """
    Transaction Service API.

    Main entry point with API information.
    """
    return {
        "name": "Transaction Service API",
        "version": "1.0.0",
        "description": "Microservice for financial transactions",
        "endpoints": {
            "health": "/health",
            "ready": "/ready",
            "docs": "/api/docs",
            "deposits": "/api/v1/deposits",
            "withdrawals": "/api/v1/withdrawals",
            "transfers": "/api/v1/transfers",
            "transfer_limits": "/api/v1/transfer-limits/{account_number}",
            "transaction_logs": "/api/v1/transaction-logs/{account_number}",
        },
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        "app.main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=settings.DEBUG,
        log_level="info",
    )
